# Generated by Django 2.1.2 on 2018-10-03 01:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2018, 10, 3, 1, 31, 11, 189545))),
                ('date_updated', models.DateTimeField(default=datetime.datetime(2018, 10, 3, 1, 31, 11, 189578))),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot', models.TextField()),
                ('likes', models.PositiveIntegerField(default=0)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2018, 10, 3, 1, 31, 11, 190050))),
                ('date_updated', models.DateTimeField(default=datetime.datetime(2018, 10, 3, 1, 31, 11, 190069))),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieEditHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor', models.CharField(max_length=64)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2018, 10, 3, 1, 31, 11, 190518))),
                ('date_updated', models.DateTimeField(default=datetime.datetime(2018, 10, 3, 1, 31, 11, 190536))),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie')),
            ],
        ),
    ]
