# Generated by Django 2.1.2 on 2018-10-03 01:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 3, 1, 36, 27, 792249)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 3, 1, 36, 27, 792278)),
        ),
        migrations.AlterField(
            model_name='moviedetails',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 3, 1, 36, 27, 792713)),
        ),
        migrations.AlterField(
            model_name='moviedetails',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 3, 1, 36, 27, 792733)),
        ),
        migrations.AlterField(
            model_name='movieedithistory',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 3, 1, 36, 27, 793227)),
        ),
        migrations.AlterField(
            model_name='movieedithistory',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 3, 1, 36, 27, 793245)),
        ),
    ]
