# Generated by Django 2.1.2 on 2018-10-03 03:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20181003_0343'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot', models.TextField()),
                ('likes', models.PositiveIntegerField(default=0)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2018, 10, 3, 3, 48, 14, 893743))),
                ('date_updated', models.DateTimeField(default=datetime.datetime(2018, 10, 3, 3, 48, 14, 893762))),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='moviedetails',
            name='movie',
        ),
        migrations.AlterField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 3, 3, 48, 14, 893266)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 3, 3, 48, 14, 893295)),
        ),
        migrations.AlterField(
            model_name='movieedithistory',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 3, 3, 48, 14, 894202)),
        ),
        migrations.AlterField(
            model_name='movieedithistory',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 3, 3, 48, 14, 894220)),
        ),
        migrations.DeleteModel(
            name='MovieDetails',
        ),
        migrations.AddField(
            model_name='moviedetail',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie'),
        ),
    ]
