# Generated by Django 2.1.2 on 2018-10-03 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20181003_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedetail',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='plot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 3, 6, 47, 17, 41317)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 3, 6, 47, 17, 41361)),
        ),
        migrations.AlterField(
            model_name='movieedithistory',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 3, 6, 47, 17, 41904)),
        ),
        migrations.AlterField(
            model_name='movieedithistory',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 3, 6, 47, 17, 41924)),
        ),
        migrations.DeleteModel(
            name='MovieDetail',
        ),
    ]
