# Generated by Django 2.1.2 on 2018-10-03 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20181003_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 3, 11, 20, 35, 894226)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 3, 11, 20, 35, 894244)),
        ),
        migrations.AlterField(
            model_name='movieedithistory',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 3, 11, 20, 35, 894557)),
        ),
        migrations.AlterField(
            model_name='movieedithistory',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 3, 11, 20, 35, 894571)),
        ),
    ]
