# Generated by Django 2.1.2 on 2018-10-04 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20181003_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieedithistory',
            name='movie',
        ),
        migrations.AlterField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 4, 11, 29, 5, 507489)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 4, 11, 29, 5, 507512)),
        ),
        migrations.DeleteModel(
            name='MovieEditHistory',
        ),
    ]
